"""empty message

Revision ID: 812bab70cef5
Revises: 
Create Date: 2020-06-01 14:31:53.758105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812bab70cef5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
